export const fakeSquad = {
  "1": {
    number: "1",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/55282-1663574299.jpg?lm=1",
    playerName: "Tătărușanu",
    firstName: "Ciprian",
    lastName: "Tătărușanu",
    alias: "",
    id: "55282",
    position: "Goalkeeper",
    posSort: 1,
    formationPosition: 1,
    preferredFoot: "2",
    tm_position: {
      left: 40,
      top: 80,
    },
    marketValue: "400",
    marketValueCurrency: "€",
    marketValueNumeral: "k",
    age: "38",
    countryID: "140",
    countryName: "Romania",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/140.png?lm=1520611569",
    secondCountryID: "",
    secondCountryImage: "",
    secondCountryName: "",
  },
  "2": {
    number: "28",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/521964-1682063635.jpg?lm=1",
    playerName: "Thiaw",
    firstName: "Malick",
    lastName: "Thiaw",
    alias: "",
    id: "521964",
    position: "Defender",
    posSort: 2,
    formationPosition: 3,
    preferredFoot: "2",
    tm_position: {
      left: 40,
      top: 62,
    },
    marketValue: "30,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "22",
    countryID: "40",
    countryName: "Germany",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/40.png?lm=1520612525",
    secondCountryID: "49",
    secondCountryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/49.png?lm=1520611569",
    secondCountryName: "Finland",
  },
  "3": {
    number: "24",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/48859-1661514194.jpg?lm=1",
    playerName: "Kjaer",
    firstName: "Simon",
    lastName: "Kjaer",
    alias: "",
    id: "48859",
    position: "Defender",
    posSort: 2,
    formationPosition: 3,
    preferredFoot: "2",
    tm_position: {
      left: 15,
      top: 61,
    },
    marketValue: "2,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "34",
    countryID: "39",
    countryName: "Denmark",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/39.png?lm=1520611569",
    secondCountryID: "",
    secondCountryImage: "",
    secondCountryName: "",
  },
  "4": {
    number: "20",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/585949-1684854558.jpg?lm=1",
    playerName: "Kalulu",
    firstName: "Pierre",
    lastName: "Kalulu",
    alias: "",
    id: "585949",
    position: "Defender",
    posSort: 2,
    formationPosition: 3,
    preferredFoot: "2",
    tm_position: {
      left: 65,
      top: 61,
    },
    marketValue: "25,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "23",
    countryID: "50",
    countryName: "France",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/50.png?lm=1520611569",
    secondCountryID: "193",
    secondCountryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/193.png?lm=1520611569",
    secondCountryName: "DR Congo",
  },
  "5": {
    number: "56",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/381950-1609842664.jpg?lm=1",
    playerName: "Saelemaekers",
    firstName: "Alexis",
    lastName: "Saelemaekers",
    alias: "",
    id: "381950",
    position: "Striker",
    posSort: 4,
    formationPosition: 8,
    preferredFoot: "2",
    tm_position: {
      left: 65,
      top: 34,
    },
    marketValue: "10,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "24",
    countryID: "19",
    countryName: "Belgium",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/19.png?lm=1520611569",
    secondCountryID: "",
    secondCountryImage: "",
    secondCountryName: "",
  },
  "6": {
    number: "8",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/397033-1688389270.jpg?lm=1",
    playerName: "Tonali",
    firstName: "Sandro",
    lastName: "Tonali",
    alias: "",
    id: "397033",
    position: "Midfielder",
    posSort: 3,
    formationPosition: 6,
    preferredFoot: "2",
    tm_position: {
      left: 52,
      top: 43,
    },
    marketValue: "40,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "23",
    countryID: "75",
    countryName: "Italy",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/75.png?lm=1520611569",
    secondCountryID: "",
    secondCountryImage: "",
    secondCountryName: "",
  },
  "7": {
    number: "33",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/259953-1661350943.jpg?lm=1",
    playerName: "Krunic",
    firstName: "Rade",
    lastName: "Krunic",
    alias: "",
    id: "259953",
    position: "Midfielder",
    posSort: 3,
    formationPosition: 6,
    preferredFoot: "2",
    tm_position: {
      left: 30,
      top: 43,
    },
    marketValue: "8,50",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "30",
    countryID: "24",
    countryName: "Bosnia-Herzegovina",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/24.png?lm=1569523290",
    secondCountryID: "",
    secondCountryImage: "",
    secondCountryName: "",
  },
  "8": {
    number: "19",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/339808-1663574533.jpg?lm=1",
    playerName: "Hernández",
    firstName: "Theo",
    lastName: "Hernández",
    alias: "",
    id: "339808",
    position: "Defender",
    posSort: 2,
    formationPosition: 9,
    preferredFoot: "1",
    tm_position: {
      left: 15,
      top: 34,
    },
    marketValue: "60,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "26",
    countryID: "50",
    countryName: "France",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/50.png?lm=1520611569",
    secondCountryID: "157",
    secondCountryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/157.png?lm=1520611569",
    secondCountryName: "Spain",
  },
  "9": {
    number: "10",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/314678-1632307989.jpg?lm=1",
    playerName: "Díaz",
    firstName: "Brahim",
    lastName: "Díaz",
    alias: "",
    id: "314678",
    position: "Midfielder",
    posSort: 3,
    formationPosition: 10,
    preferredFoot: "3",
    tm_position: {
      left: 50,
      top: 20,
    },
    marketValue: "20,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "24",
    countryID: "107",
    countryName: "Morocco",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/107.png?lm=1520611569",
    secondCountryID: "157",
    secondCountryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/157.png?lm=1520611569",
    secondCountryName: "Spain",
  },
  "10": {
    number: "9",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/82442-1661514565.jpg?lm=1",
    playerName: "Giroud",
    firstName: "Olivier",
    lastName: "Giroud",
    alias: "",
    id: "82442",
    position: "Striker",
    posSort: 4,
    formationPosition: 10,
    preferredFoot: "1",
    tm_position: {
      left: 40,
      top: 3,
    },
    marketValue: "4,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "37",
    countryID: "50",
    countryName: "France",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/50.png?lm=1520611569",
    secondCountryID: "",
    secondCountryImage: "",
    secondCountryName: "",
  },
  "11": {
    number: "17",
    playerImage:
      "https://img.a.transfermarkt.technology/portrait/medium/357164-1661352687.jpg?lm=1",
    playerName: "Leão",
    firstName: "Rafael",
    lastName: "Leão",
    alias: "",
    id: "357164",
    position: "Striker",
    posSort: 4,
    formationPosition: 14,
    preferredFoot: "2",
    tm_position: {
      left: 30,
      top: 20,
    },
    marketValue: "90,00",
    marketValueCurrency: "€",
    marketValueNumeral: "mil.",
    age: "24",
    countryID: "136",
    countryName: "Portugal",
    countryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/136.png?lm=1520611569",
    secondCountryID: "6",
    secondCountryImage:
      "https://tmssl.akamaized.net/images/flagge/verysmall/6.png?lm=1520611569",
    secondCountryName: "Angola",
  },
};
