export const dummy3 = {
  json: [
    {
      height: "1,95",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1577919600,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "3455",
      name: "Zlatan Ibrahimović",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/3455-1579506060.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 40,
      dateOfBirth: 370911600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/zlatan-ibrahimovic-ac-mailand-1603008323-49388.jpg?lm=1603008348",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 147,
          name: "Sweden",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/147.png?lm=1520611569",
        },
        {
          id: 24,
          name: "Bosnia-Herzegovina",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/24.png?lm=1569523290",
        },
      ],
      marketValue: {
        value: 2000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,93",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1634076000,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "22141",
      name: "Antonio Mirante",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/22141-1663574908.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 38,
      dateOfBirth: 426463200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/antonio-mirante-ac-milan-1637570885-75232.jpg?lm=1637570897",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 100000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,91",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1598911200,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "48859",
      name: "Simon Kjaer",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/48859-1661514194.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 33,
      dateOfBirth: 606870000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/simon-kjaer-milan-2022-2023-1663575580-92624.jpg?lm=1663575602",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 39,
          name: "Denmark",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/39.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 3500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,98",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1599775200,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "55282",
      name: "Ciprian Tătărușanu",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/55282-1663574299.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 36,
      dateOfBirth: 508287600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/ciprian-tatarusanu-fc-steaua-1707833517-129237.jpg?lm=1707833537",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 140,
          name: "Romania",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/140.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 400000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,92",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1626472800,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "82442",
      name: "Olivier Giroud",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/82442-1661514565.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 35,
      dateOfBirth: 528418800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/olivier-giroud-milan-1630616830-70281.jpg?lm=1630616849",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 4000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,73",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1656626400,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "130365",
      name: "Alessandro Florenzi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/130365-1663574873.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 31,
      dateOfBirth: 668646000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/alessandro-florenzi-milan-2022-2023-1666010293-94387.jpg?lm=1666010308",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        third: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 2000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,89",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1656972000,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "148368",
      name: "Divock Origi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/148368-1709306595.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 27,
      dateOfBirth: 798156000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/divock-origi-milan-2022-1660905714-90568.jpg?lm=1660905725",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        third: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 19,
          name: "Belgium",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/19.png?lm=1520611569",
        },
        {
          id: 82,
          name: "Kenya",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/82.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 6000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,89",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1630274400,
      contractUntil: 1751234400,
      captain: false,
      lastClub: {
        id: "631",
        name: "Chelsea",
        fullName: "Chelsea FC",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/631.png?lm=1682435911",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "182618",
      name: "Tiemoué Bakayoko",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/182618-1661350547.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 27,
      dateOfBirth: 777074400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/tiemoue-bakayoko-milan-1633953444-72520.jpg?lm=1633953468",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
        {
          id: 38,
          name: "Cote d'Ivoire",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/38.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 2500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,91",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1625090400,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "182906",
      name: "Mike Maignan",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/182906-1681459155.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 26,
      dateOfBirth: 804722400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/maignan-mike-2023-2024-france-1707130636-128521.jpg?lm=1707130646",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
        {
          id: 252,
          name: "French Guiana",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/252.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 45000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1599861600,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "187587",
      name: "Ante Rebic",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/187587-1696076377.png?lm=1",
      imageLarge: null,
      imageSource: "Beşiktaş",
      shirtNumber: null,
      age: 28,
      dateOfBirth: 748562400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/ante-rebic-besiktas-2023-24-1690817198-112871.jpg?lm=1690817210",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        second: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        third: {
          id: "13",
          name: "Second Striker",
          shortName: "SS",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 37,
          name: "Croatia",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/37.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 6000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,84",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1562536800,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "259953",
      name: "Rade Krunic",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/259953-1661350943.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 28,
      dateOfBirth: 749948400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/rade-krunic-fenerbahce-1705572409-126743.jpg?lm=1705572459",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 24,
          name: "Bosnia-Herzegovina",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/24.png?lm=1569523290",
        },
      ],
      marketValue: {
        value: 10000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,76",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1435701600,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "262523",
      name: "Davide Calabria",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/262523-1684856316.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 25,
      dateOfBirth: 849826800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/davide-calabria-milan-2023-2324-1693317848-115280.jpg?lm=1693317998",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        third: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 20000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,82",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1626559200,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "296422",
      name: "Fodé Ballo-Touré",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/296422-1614110347.jpg?lm=1",
      imageLarge: null,
      imageSource: "AS Monaco",
      shirtNumber: null,
      age: 25,
      dateOfBirth: 852246000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/ballo-toure-fode-senegal-2022-1705066080-126207.jpg?lm=1705066122",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: {
          id: "9",
          name: "Left Midfield",
          shortName: "LM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 149,
          name: "Senegal",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/149.png?lm=1520611569",
        },
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 3500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1625090400,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "303254",
      name: "Fikayo Tomori",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/303254-1684856117.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 882486000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/fikayo-tomori-milan-2023-2324-1693318944-115302.jpg?lm=1693318971",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        third: null,
      },
      nationalities: [
        {
          id: 189,
          name: "England",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569",
        },
        {
          id: 80,
          name: "Canada",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/80.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 40000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,70",
      foot: "both",
      injury: null,
      suspension: null,
      joined: 1626645600,
      contractUntil: 1814306400,
      captain: false,
      lastClub: {
        id: "418",
        name: "Real Madrid",
        fullName: "Real Madrid",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/418.png?lm=1697726166",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "314678",
      name: "Brahim Díaz",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/314678-1632307989.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 22,
      dateOfBirth: 933631200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/brahim-diaz-real-madrid-2023-24-1710143453-131411.jpg?lm=1710143473",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
        second: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        third: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 107,
          name: "Morocco",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/107.png?lm=1520611569",
        },
        {
          id: 157,
          name: "Spain",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/157.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 20000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1498860000,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "323167",
      name: "Matteo Gabbia",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/323167-1661351918.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 22,
      dateOfBirth: 940456800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/matteo-gabbia-milan-2022-2023-1663575627-92625.jpg?lm=1663575662",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 5000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,84",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1562364000,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "339808",
      name: "Theo Hernández",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/339808-1663574533.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 876088800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/theo-hernandez-milan-2023-2324-1692879363-114764.jpg?lm=1692879376",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: {
          id: "9",
          name: "Left Midfield",
          shortName: "LM",
          group: "Midfielder",
        },
        third: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
        {
          id: 157,
          name: "Spain",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/157.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 60000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,75",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1564869600,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "351816",
      name: "Ismaël Bennacer",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/351816-1663575089.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 880930800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/ismael-bennacer-milan-2023-2324-1707126796-128471.jpg?lm=1707126803",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
        third: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 4,
          name: "Algeria",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/4.png?lm=1520611569",
        },
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 40000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,88",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1564610400,
      contractUntil: 1845928800,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "357164",
      name: "Rafael Leão",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/357164-1661352687.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 23,
      dateOfBirth: 928965600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/rafael-leao-milan-2023-2324-1697025574-118943.jpg?lm=1697025593",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        second: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        third: null,
      },
      nationalities: [
        {
          id: 136,
          name: "Portugal",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/136.png?lm=1520611569",
        },
        {
          id: 6,
          name: "Angola",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/6.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 90000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,73",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1661983200,
      contractUntil: 1719698400,
      captain: false,
      lastClub: {
        id: "131",
        name: "Barcelona",
        fullName: "FC Barcelona",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/131.png?lm=1406739548",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "361104",
      name: "Sergiño Dest",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/361104-1694588343.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 21,
      dateOfBirth: 973206000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/sergino-dest-of-psv-eindhoven-2023-1697541651-119619.jpg?lm=1697541684",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        third: null,
      },
      nationalities: [
        {
          id: 184,
          name: "United States",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/184.png?lm=1520611569",
        },
        {
          id: 122,
          name: "Netherlands",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/122.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 10000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,80",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1598911200,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "381950",
      name: "Alexis Saelemaekers",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/381950-1609842664.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 23,
      dateOfBirth: 930434400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/saelemaekers-alexis-bologna-2023-2024-1705062252-126177.jpg?lm=1705062267",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        second: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
        third: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 19,
          name: "Belgium",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/19.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 15000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,88",
      foot: "both",
      injury: null,
      suspension: null,
      joined: 1530396000,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "392538",
      name: "Tommaso Pobega",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/392538-1661767249.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 22,
      dateOfBirth: 931989600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/tommaso-pobega-milan-2023-2324-1693317958-115281.jpg?lm=1693318003",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 14000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1630274400,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "395236",
      name: "Yacine Adli",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/395236-1656579831.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 21,
      dateOfBirth: 964821600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/yacine-adli-milan-2023-2324-1707129966-128510.jpg?lm=1707129974",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
        {
          id: 4,
          name: "Algeria",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/4.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 8000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,81",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1625695200,
      contractUntil: 1845928800,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "397033",
      name: "Sandro Tonali",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/397033-1688389270.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 22,
      dateOfBirth: 957736800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/sandro-tonali-1690542295-112704.jpg?lm=1690542312",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 50000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,92",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1659391200,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "435772",
      name: "Charles De Ketelaere",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/435772-1659601388.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 21,
      dateOfBirth: 984178800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/charles-de-ketelaere-atalanta-2023-2324-1692880195-114771.jpg?lm=1692880218",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
        second: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        third: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 19,
          name: "Belgium",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/19.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 22000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,74",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1657144800,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "449151",
      name: "Junior Messias",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/449151-1663575000.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 31,
      dateOfBirth: 674085600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/junior-messias-genoa-2023-2324-1697182850-119178.jpg?lm=1697182860",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        second: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
        third: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 26,
          name: "Brazil",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
        },
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 4500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,95",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1672700400,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "495722",
      name: "Devis Vásquez",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/495722-1675072031.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 894924000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/devis-vasquez-1678812064-103609.jpg?lm=1678812077",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 83,
          name: "Colombia",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/83.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 350000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,83",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1661983200,
      contractUntil: 1751234400,
      captain: false,
      lastClub: {
        id: "82",
        name: "VfL Wolfsburg",
        fullName: "VfL Wolfsburg",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/82.png?lm=1503060755",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "503881",
      name: "Aster Vranckx",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/503881-1657202999.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 19,
      dateOfBirth: 1033682400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/vranckx-aster-vfl-wolfsburg-2023-2024-1705063187-126183.jpg?lm=1705063328",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 19,
          name: "Belgium",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/19.png?lm=1520611569",
        },
        {
          id: 193,
          name: "DR Congo",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/193.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 8500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,94",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1661724000,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "521964",
      name: "Malick Thiaw",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/521964-1682063635.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 20,
      dateOfBirth: 997221600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/malick-thiaw-milan-2023-2324-1693319244-115304.jpg?lm=1693319588",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
      },
      nationalities: [
        {
          id: 40,
          name: "Germany",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/40.png?lm=1520612525",
        },
        {
          id: 49,
          name: "Finland",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/49.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 20000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,82",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1598911200,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "585949",
      name: "Pierre Kalulu",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/585949-1684854558.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 22,
      dateOfBirth: 960156000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/pierre-kalulu-ac-milan-2023-2024-1036415364hjpg-1705402028-126494.jpg?lm=1705402037",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        third: null,
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
        {
          id: 193,
          name: "DR Congo",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/193.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 30000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,95",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1656626400,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "592924",
      name: "Andreas Jungdal",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/592924-1710321790.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 20,
      dateOfBirth: 1014332400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/andreas-jungdal-cremonese-23-24-1710855626-132091.jpg?lm=1710855638",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 39,
          name: "Denmark",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/39.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 300000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,78",
      foot: "left",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "669793",
      name: "Andrea Bozzolan",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/669793-1699705385.png?lm=1",
      imageLarge: null,
      imageSource: "acperugiacalcio.com",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 1077490800,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 125000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,89",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "692349",
      name: "Andrei Coubiș",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/692349-1655210355.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 1064786400,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        third: null,
      },
      nationalities: [
        {
          id: 140,
          name: "Romania",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/140.png?lm=1520611569",
        },
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 100000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,92",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1643151600,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "698548",
      name: "Marko Lazetic",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/698548-1665512796.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 1074726000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/marko-lazetic-altach-2023-1679393332-104019.jpg?lm=1679393353",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 215,
          name: "Serbia",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/215.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 2000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,75",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "815556",
      name: "Antonio Gala",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/default.jpg?lm=1",
      imageLarge: null,
      imageSource: "",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 1086559200,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 75000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,89",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "815563",
      name: "Lapo Nava",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/815563-1681206054.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 1074726000,
      heroImage: null,
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 150000,
        currency: "€",
        progression: null,
      },
    },
  ],
};
