export const dummy2 = {
  json: [
    {
      height: "1,76",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1404684000,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "3182",
      name: "Ashley Cole",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/3182-1683297696.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 33,
      dateOfBirth: 346114800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/ashley-cole-1404934592-1264.jpg?lm=1483605576",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 189,
          name: "England",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/189.png?lm=1520611569",
        },
        {
          id: 17,
          name: "Barbados",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/17.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1278540000,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "4310",
      name: "Bogdan Lobonț",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/4310-1408617141.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 36,
      dateOfBirth: 253926000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/bogdan-lobont-1418383377-3958.jpg?lm=1483605894",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 140,
          name: "Romania",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/140.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 100000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,83",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1404165600,
      contractUntil: 1710941351,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "5486",
      name: "Seydou Keita",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/5486-1448466474.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 34,
      dateOfBirth: 316825200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/seydou-keita-mali-1587980400-37118.jpg?lm=1587980425",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: {
          id: "9",
          name: "Left Midfield",
          shortName: "LM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 105,
          name: "Mali",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/105.png?lm=1520611569",
        },
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1309471200,
      contractUntil: 1710941351,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "5825",
      name: "Marco Borriello",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/5825-1455533007.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 32,
      dateOfBirth: 393199200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/marco-borriello-1418652072-3981.jpg?lm=1483605897",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,90",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1374703200,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "5880",
      name: "Morgan De Sanctis",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/5880-1455553786.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 37,
      dateOfBirth: 228178800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/morgan-de-sanctis-1418383284-3956.jpg?lm=1483605894",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 700000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,84",
      foot: "both",
      injury: null,
      suspension: null,
      joined: 1025474400,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "5947",
      name: "Daniele De Rossi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/5947-1454935412.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 30,
      dateOfBirth: 427845600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/daniele-de-rossi-boca-1564483488-24036.jpg?lm=1564483498",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 11000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,80",
      foot: "both",
      injury: null,
      suspension: null,
      joined: 725842800,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "5958",
      name: "Francesco Totti",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/5958-1448466835.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 37,
      dateOfBirth: 212626800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/francesco-totti-abschied-winken-1601021419-47804.jpg?lm=1601021441",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "13",
          name: "Second Striker",
          shortName: "SS",
          group: "Striker",
        },
        second: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1374098400,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "18301",
      name: "Maicon",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/18301-1505484617.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 32,
      dateOfBirth: 364946400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/maicon-douglas-inter-2010-1704213410-125341.jpg?lm=1704213451",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 26,
          name: "Brazil",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 2000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,76",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1405029600,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "20586",
      name: "Urby Emanuelson",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/20586-1629451683.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 28,
      dateOfBirth: 519256800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/urby-emanuelson-fc-utrecht-1621853094-63321.jpg?lm=1621853104",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        third: null,
      },
      nationalities: [
        {
          id: 122,
          name: "Netherlands",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/122.png?lm=1520611569",
        },
        {
          id: 161,
          name: "Suriname",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/161.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 2500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,80",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1343772000,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "21876",
      name: "Federico Balzaretti",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/21876-1418385188.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 32,
      dateOfBirth: 376441200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/federico-balzaretti-1418385328-3968.jpg?lm=1483605895",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: {
          id: "9",
          name: "Left Midfield",
          shortName: "LM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 700000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,91",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1309471200,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "24001",
      name: "Gianluca Curci",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/24001-1440399555.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 28,
      dateOfBirth: 489967200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/gianluca-curci-1418382969-3953.jpg?lm=1483605894",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1358895600,
      contractUntil: 1710941352,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "24977",
      name: "Vasilios Torosidis",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/24977-1459341419.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 29,
      dateOfBirth: 487202400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/vasilis-torosidis-1418383650-3961.jpg?lm=1483605894",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        third: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 56,
          name: "Greece",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/56.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 5000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,79",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1375912800,
      contractUntil: 1710941352,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "33481",
      name: "Gervinho",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/33481-1630525113.png?lm=1",
      imageLarge: null,
      imageSource: "www.trabzonspor.org.tr",
      shirtNumber: null,
      age: 27,
      dateOfBirth: 549064800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/gervinho-trabzonspor-2021-2022-1639135589-76494.jpg?lm=1639135597",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        second: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        third: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 38,
          name: "Cote d'Ivoire",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/38.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 18500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,84",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1409349600,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "41112",
      name: "Jose Cholevas",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/41112-1418385082.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 30,
      dateOfBirth: 457135200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/jose-cholevas-olympiakos-piraus-joao-cancelo-manchester-city-1632498877-71665.jpg?lm=1632498897",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: {
          id: "9",
          name: "Left Midfield",
          shortName: "LM",
          group: "Midfielder",
        },
        third: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
      },
      nationalities: [
        {
          id: 56,
          name: "Greece",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/56.png?lm=1520611569",
        },
        {
          id: 40,
          name: "Germany",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/40.png?lm=1520612525",
        },
      ],
      marketValue: {
        value: 2000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,77",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1404165600,
      contractUntil: 1710962640,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "41982",
      name: "Radja Nainggolan",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/41982-1666894874.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 26,
      dateOfBirth: 578700000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/radja-nainggolan-1708139691-129623.jpeg?lm=1708139705",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 19,
          name: "Belgium",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/19.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 24000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,78",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1314741600,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "44162",
      name: "Miralem Pjanic",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/44162-1643282459.png?lm=1",
      imageLarge: null,
      imageSource: "Besiktas",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 639007200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/miralem-pjanic-besiktas-2021-22-1633106009-72011.jpg?lm=1633106021",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 24,
          name: "Bosnia-Herzegovina",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/24.png?lm=1569523290",
        },
        {
          id: 99,
          name: "Luxembourg",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/99.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 28000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,93",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1422831600,
      contractUntil: false,
      captain: false,
      lastClub: {
        id: "1627",
        name: "Catania",
        fullName: "Catania FC",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/1627.png?lm=1692861464",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "51186",
      name: "Nicolás Spolli",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/51186-1454584736.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 31,
      dateOfBirth: 414543600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/nicolas-spolli-1416927925-3103.jpg?lm=1483605803",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 9,
          name: "Argentina",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
        },
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 3500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1342562400,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "54929",
      name: "Leandro Castán",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/54929-1448466044.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 27,
      dateOfBirth: 531529200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/leandro-castan-vasco-1605258773-51398.jpg?lm=1605258785",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 26,
          name: "Brazil",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
        },
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 12500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,84",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1422313200,
      contractUntil: 1710941352,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "57480",
      name: "Mapou Yanga-Mbiwa",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/57480-1418383803.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 25,
      dateOfBirth: 611186400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/yanga-mbiwa-mapou-2016-2017-olympique-lyonnais-1707140160-128548.jpg?lm=1707140173",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        third: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 50,
          name: "France",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/50.png?lm=1520611569",
        },
        {
          id: 138,
          name: "Central African Republic",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/138.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 6000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1373925600,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "68864",
      name: "Kevin Strootman",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/68864-1661426336.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 634863600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/kevin-strootman-genoa-1611570689-55226.jpg?lm=1611570714",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 122,
          name: "Netherlands",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/122.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 22500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,82",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1377640800,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "69374",
      name: "Adem Ljajic",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/69374-1695220088.png?lm=1",
      imageLarge: null,
      imageSource: "Fatih Karagümrük",
      shirtNumber: null,
      age: 22,
      dateOfBirth: 686095200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/adem-ljajic-fatih-karagumruk-1692891563-114818.jpg?lm=1692891592",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
        second: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        third: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 215,
          name: "Serbia",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/215.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 13500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,79",
      foot: "both",
      injury: null,
      suspension: null,
      joined: 1422658800,
      contractUntil: 1710941352,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "75287",
      name: "Seydou Doumbia",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/75287-1510680050.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 26,
      dateOfBirth: 567903600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/doumbia-seydou-1533023148-16898.jpg?lm=1533023153",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: {
          id: "13",
          name: "Second Striker",
          shortName: "SS",
          group: "Striker",
        },
        third: null,
      },
      nationalities: [
        {
          id: 38,
          name: "Cote d'Ivoire",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/38.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 20000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,88",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1373580000,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "80894",
      name: "Lukasz Skorupski",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/80894-1595848892.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 23,
      dateOfBirth: 673394400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/lukasz-skorupski-bologna-2023-24-1695975225-117992.jpg?lm=1695975240",
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 135,
          name: "Poland",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/135.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,73",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1405461600,
      contractUntil: 1767135600,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "81455",
      name: "Juan Iturbe",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/81455-1456821893.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 21,
      dateOfBirth: 739144800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/juan-iturbe-aris-saloniki-2023-1686756149-109229.jpg?lm=1686756176",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        second: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        third: {
          id: "13",
          name: "Second Striker",
          shortName: "SS",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 132,
          name: "Paraguay",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/132.png?lm=1520611569",
        },
        {
          id: 9,
          name: "Argentina",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 19000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,89",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1406152800,
      contractUntil: false,
      captain: false,
      lastClub: {
        id: "1390",
        name: "Cagliari Calcio",
        fullName: "Cagliari Calcio",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/1390.png?lm=1626441409",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "87210",
      name: "Davide Astori",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/87210-1520162249.jpg?lm=1",
      imageLarge: null,
      imageSource: "Getty Images",
      shirtNumber: null,
      age: 27,
      dateOfBirth: 536972400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/davide-astori-ac-florenz-1520163295-14284.jpg?lm=1520163306",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 8000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,82",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1372629600,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "88683",
      name: "Mattia Destro",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/88683-1695031437.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 23,
      dateOfBirth: 669423600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/mattia-destro-empoli-2022-23-1660214268-89975.jpg?lm=1660214290",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 16500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,88",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1422745200,
      contractUntil: false,
      captain: false,
      lastClub: {
        id: "1390",
        name: "Cagliari Calcio",
        fullName: "Cagliari Calcio",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/1390.png?lm=1626441409",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "92141",
      name: "Víctor Ibarbo",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/92141-1616061239.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 24,
      dateOfBirth: 643068000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/victor-ibarbo-1696132390-118106.jpg?lm=1696132409",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "13",
          name: "Second Striker",
          shortName: "SS",
          group: "Striker",
        },
        second: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        third: null,
      },
      nationalities: [
        {
          id: 83,
          name: "Colombia",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/83.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 8500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1409004000,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "104752",
      name: "Konstantinos Manolas",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/104752-1663850126.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 23,
      dateOfBirth: 676850400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/konstantinos-manolas-olympiakos-2021-22-1645541056-80740.jpg?lm=1645541067",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 56,
          name: "Greece",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/56.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 15000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,73",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1341180000,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "130365",
      name: "Alessandro Florenzi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/130365-1663574873.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 23,
      dateOfBirth: 668646000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/alessandro-florenzi-milan-2022-2023-1666010293-94387.jpg?lm=1666010308",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        third: {
          id: "8",
          name: "Right Midfield",
          shortName: "RM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 14000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,80",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1404165600,
      contractUntil: 1751234400,
      captain: false,
      lastClub: {
        id: "189",
        name: "Boca Juniors",
        fullName: "CA Boca Juniors",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/189.png?lm=1511621129",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "166237",
      name: "Leandro Paredes",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/166237-1692881087.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 20,
      dateOfBirth: 772840800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/leandro-paredes-psg-2021-22-1661862362-91353.jpg?lm=1661862376",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 9,
          name: "Argentina",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 3700000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,82",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1405634400,
      contractUntil: 1719698400,
      captain: false,
      lastClub: {
        id: "36",
        name: "Fenerbahce",
        fullName: "Fenerbahce",
        image:
          "https://tmssl.akamaized.net/images/wappen/medium/36.png?lm=1406739123",
        nationalTeam: "",
        flag: null,
        marketValue: null,
        mainCompetition: null,
      },
      isLoan: true,
      wasLoan: null,
      id: "170838",
      name: "Salih Uçan",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/170838-1696076118.png?lm=1",
      imageLarge: null,
      imageSource: "Beşiktaş",
      shirtNumber: null,
      age: 20,
      dateOfBirth: 757810800,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/salih-ucan-besiktas-1691738832-113846.jpg?lm=1691738869",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
        third: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 174,
          name: "Türkiye",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/174.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 5000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,78",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: false,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "186393",
      name: "Tomas Vestenicky",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/186393-1607016482.png?lm=1",
      imageLarge: null,
      imageSource: "www.cracovia.pl",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 828741600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/tomas-vestenicky-cracovia-1620978375-62441.jpg?lm=1620978390",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        third: {
          id: "13",
          name: "Second Striker",
          shortName: "SS",
          group: "Striker",
        },
      },
      nationalities: [
        {
          id: 154,
          name: "Slovakia",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/154.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 200000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1341093600,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "197747",
      name: "Alessio Romagnoli",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/197747-1650543426.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 19,
      dateOfBirth: 789865200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/alessio-romagnoli-lazio-2023-2324-1693317750-115278.jpg?lm=1693317987",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 6500000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,80",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1404165600,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "234523",
      name: "Antonio Sanabria",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/234523-1692963077.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 825894000,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/antonio-sanabria-torino-2024-2324-1707815845-129186.jpg?lm=1707815865",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "14",
          name: "Centre-Forward",
          shortName: "CF",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 132,
          name: "Paraguay",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/132.png?lm=1520611569",
        },
        {
          id: 157,
          name: "Spain",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/157.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 4000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,85",
      foot: "both",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "238947",
      name: "Elio Capradossi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/238947-1692962507.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 826498800,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 250000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,71",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "239583",
      name: "Jacopo Ferri",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/239583-1585725855.jpeg?lm=1",
      imageLarge: null,
      imageSource: "latinacalcio1932.com",
      shirtNumber: null,
      age: 19,
      dateOfBirth: 797032800,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 125000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,71",
      foot: "left",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "239599",
      name: "Massimo Sammartino",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/239599-1461939768.png?lm=1",
      imageLarge: null,
      imageSource: "uspistoiese1921.it",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 810511200,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
        second: {
          id: "9",
          name: "Left Midfield",
          shortName: "LM",
          group: "Midfielder",
        },
        third: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 50000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,82",
      foot: "right",
      injury: null,
      suspension: null,
      joined: 1404165600,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "240365",
      name: "Michele Somma",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/240365-1544776751.jpg?lm=1",
      imageLarge: null,
      imageSource: "imago images",
      shirtNumber: null,
      age: 19,
      dateOfBirth: 795308400,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/michele-somma-1418385479-3970.jpg?lm=1483605895",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        second: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 200000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1751234400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "240897",
      name: "Arturo Calabresi",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/240897-1633101808.jpg?lm=1",
      imageLarge: null,
      imageSource: "uslecce.it",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 827017200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/arturo-calabresi-lecce-1637162124-74888.jpg?lm=1637162135",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "5",
          name: "Right-Back",
          shortName: "RB",
          group: "Defender",
        },
        second: {
          id: "3",
          name: "Centre-Back",
          shortName: "CB",
          group: "Defender",
        },
        third: {
          id: "4",
          name: "Left-Back",
          shortName: "LB",
          group: "Defender",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 300000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,89",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "250937",
      name: "Gabriele Marchegiani",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/250937-1636555679.png?lm=1",
      imageLarge: null,
      imageSource: "actrento.com",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 833752800,
      heroImage: null,
      isGoalkeeper: true,
      positions: {
        first: {
          id: "1",
          name: "Goalkeeper",
          shortName: "GK",
          group: "Goalkeeper",
        },
        second: null,
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 100000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,75",
      foot: "right",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1719698400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "256338",
      name: "Matteo Adamo",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/256338-1657279614.jpg?lm=1",
      imageLarge: null,
      imageSource: "ancona1905.it",
      shirtNumber: null,
      age: 17,
      dateOfBirth: 838591200,
      heroImage: null,
      isGoalkeeper: false,
      positions: {
        first: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        second: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
        third: null,
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 100000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,68",
      foot: "left",
      injury: null,
      suspension: null,
      joined: 1420066800,
      contractUntil: 1814306400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "256361",
      name: "Daniele Verde",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/256361-1681205989.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 835221600,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/daniele-verde-spezia-1634302079-72946.jpg?lm=1634302088",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "12",
          name: "Right Winger",
          shortName: "RW",
          group: "Striker",
        },
        second: {
          id: "11",
          name: "Left Winger",
          shortName: "LW",
          group: "Striker",
        },
        third: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 1000000,
        currency: "€",
        progression: null,
      },
    },
    {
      height: "1,86",
      foot: "both",
      injury: null,
      suspension: null,
      joined: false,
      contractUntil: 1782770400,
      captain: false,
      lastClub: null,
      isLoan: null,
      wasLoan: null,
      id: "286297",
      name: "Lorenzo Pellegrini",
      image:
        "https://img.a.transfermarkt.technology/portrait/medium/286297-1692962972.jpg?lm=1",
      imageLarge: null,
      imageSource: "IMAGO",
      shirtNumber: null,
      age: 18,
      dateOfBirth: 835135200,
      heroImage:
        "https://tmssl.akamaized.net/images/foto/normal/lorenzo-pellegrini-roma-2023-2324-1693234983-115136.jpg?lm=1693235163",
      isGoalkeeper: false,
      positions: {
        first: {
          id: "10",
          name: "Attacking Midfield",
          shortName: "AM",
          group: "Midfielder",
        },
        second: {
          id: "7",
          name: "Central Midfield",
          shortName: "CM",
          group: "Midfielder",
        },
        third: {
          id: "6",
          name: "Defensive Midfield",
          shortName: "DM",
          group: "Midfielder",
        },
      },
      nationalities: [
        {
          id: 75,
          name: "Italy",
          image:
            "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
        },
      ],
      marketValue: {
        value: 250000,
        currency: "€",
        progression: null,
      },
    },
  ],
};
