export const dummy1 = {
  data: {
    data: [
      {
        height: "1,78",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 804549600,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "1161",
        name: "Javier Zanetti",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/1161-1463994546.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 38,
        dateOfBirth: 113785200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/javier-zanetti-jubel-inter-2009-1592311048-41572.jpg?lm=1592311024",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,81",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1075590000,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "3428",
        name: "Dejan Stankovic",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/3428-1461242093.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 33,
        dateOfBirth: 274316400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/dejan-stankovic-inter-mailand-1585581281-35266.jpg?lm=1585581294",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          third: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 215,
            name: "Serbia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/215.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 500000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,84",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1183240800,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "4314",
        name: "Cristian Chivu",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/4314-1588661612.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 31,
        dateOfBirth: 341362800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/chivu-and-mutu-romania-euro-2000-1700404407-122127.jpg?lm=1700404420",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
          third: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 140,
            name: "Romania",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/140.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 2000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,70",
        foot: "both",
        injury: null,
        suspension: null,
        joined: 1251496800,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "4673",
        name: "Wesley Sneijder",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/4673-1684166804.jpg?lm=1",
        imageLarge: null,
        imageSource: "IMAGO",
        shirtNumber: null,
        age: 28,
        dateOfBirth: 455580000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/wesley-sneijder-1415876538-2996.jpg?lm=1483605787",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: {
            id: "11",
            name: "Left Winger",
            shortName: "LW",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 122,
            name: "Netherlands",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/122.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 17000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,83",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1122847200,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "5938",
        name: "Walter Samuel",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/5938-1449586343.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 34,
        dateOfBirth: 259455600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/walter-samuel-1404673959-1068.jpg?lm=1483605550",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 157,
            name: "Spain",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/157.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1500000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,75",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1345586400,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "5962",
        name: "Antonio Cassano",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/5962-1448965838.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 29,
        dateOfBirth: 395272800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/antonio-cassano-im-trikot-der-roma-1594904790-43622.jpg?lm=1594904753",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "13",
            name: "Second Striker",
            shortName: "SS",
            group: "Striker",
          },
          second: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          third: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 6000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,77",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1357167600,
        contractUntil: 1710941353,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "6026",
        name: "Tommaso Rocchi",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/s_6026_3037_2014_03_25_1.jpg?lm=1",
        imageLarge: null,
        imageSource: "padovacalcio.it",
        shirtNumber: null,
        age: 34,
        dateOfBirth: 243471600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/tommaso-rocchi-inter-1637157142-74873.jpg?lm=1637157154",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 500000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,92",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1277935200,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "6058",
        name: "Luca Castellazzi",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/6058-1455550802.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 36,
        dateOfBirth: 174956400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/luca-castellazzi-1419246650-4236.jpg?lm=1483605926",
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 200000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,77",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1088632800,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "7520",
        name: "Esteban Cambiasso",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/7520-1462280899.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 31,
        dateOfBirth: 335397600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/esteban-cambiasso-inter-1533130573-16923.jpg?lm=1533130582",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: {
            id: "9",
            name: "Left Midfield",
            shortName: "LM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 7000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,80",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1342735200,
        contractUntil: false,
        captain: false,
        lastClub: {
          id: "1025",
          name: "Bologna",
          fullName: "Bologna FC 1909",
          image:
            "https://tmssl.akamaized.net/images/wappen/medium/1025.png?lm=1626441324",
          nationalTeam: "",
          flag: null,
          marketValue: null,
          mainCompetition: null,
        },
        isLoan: true,
        wasLoan: null,
        id: "13749",
        name: "Gaby Mudingayi",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/13749-1478679523.jpg?lm=1",
        imageLarge: null,
        imageSource: "pisachannel.tv",
        shirtNumber: null,
        age: 30,
        dateOfBirth: 370738800,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 19,
            name: "Belgium",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/19.png?lm=1520611569",
          },
          {
            id: 193,
            name: "DR Congo",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/193.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 2000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,85",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1152655200,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "18301",
        name: "Maicon",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/18301-1505484617.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 30,
        dateOfBirth: 364946400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/maicon-douglas-inter-2010-1704213410-125341.jpg?lm=1704213451",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          second: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 26,
            name: "Brazil",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 5000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,85",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341525600,
        contractUntil: false,
        captain: false,
        lastClub: {
          id: "458",
          name: "Palermo",
          fullName: "Palermo FC",
          image:
            "https://tmssl.akamaized.net/images/wappen/medium/458.png?lm=1701339000",
          nationalTeam: "",
          flag: null,
          marketValue: null,
          mainCompetition: null,
        },
        isLoan: true,
        wasLoan: null,
        id: "20003",
        name: "Matías Silvestre",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/20003-1635891092.jpg?lm=1",
        imageLarge: null,
        imageSource: "entella.it",
        shirtNumber: null,
        age: 27,
        dateOfBirth: 464911200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/matias-silvestre-1419258261-4300.jpg?lm=1483605939",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 6000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,83",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1246399200,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "22202",
        name: "Diego Milito",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/22202-1463994498.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 33,
        dateOfBirth: 297990000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/diego-milito-inter-mailand-2010-1639728515-77057.jpg?lm=1639728546",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 3000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,86",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1359586800,
        contractUntil: 1710941353,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "25441",
        name: "Zdravko Kuzmanovic",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/25441-1410340038.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 24,
        dateOfBirth: 559260000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/zdravko-kuzmanovic-fc-basel-1591964555-41263.jpg?lm=1591964544",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 215,
            name: "Serbia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/215.png?lm=1520611569",
          },
          {
            id: 148,
            name: "Switzerland",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/148.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 5000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,93",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341784800,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "28021",
        name: "Samir Handanovic",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/28021-1686929975.jpg?lm=1",
        imageLarge: null,
        imageSource: "IMAGO",
        shirtNumber: null,
        age: 27,
        dateOfBirth: 458604000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/handanovic-samir-inter-2022-2023-1663571143-92605.jpg?lm=1663571172",
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 155,
            name: "Slovenia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/155.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 24000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,83",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1264978800,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "37124",
        name: "McDonald Mariga",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/37124-1464188728.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 25,
        dateOfBirth: 544485600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/mcdonald-mariga-inter-2011-1704285742-125415.jpg?lm=1704285752",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 82,
            name: "Kenya",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/82.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 3800000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,83",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "39090",
        name: "Fredy Guarín",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/39090-1410339957.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 26,
        dateOfBirth: 520466400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/fredy-guarin-vasco-1596721917-44913.jpg?lm=1596721887",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 83,
            name: "Colombia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/83.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 18000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,76",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: 1710941354,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "39099",
        name: "Rodrigo Palacio",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/39099-1410955127.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 30,
        dateOfBirth: 381711600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/palacio-rodrigo-2007-boca-juniors-1677693728-102885.jpg?lm=1677693740",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: {
            id: "13",
            name: "Second Striker",
            shortName: "SS",
            group: "Striker",
          },
          third: {
            id: "11",
            name: "Left Winger",
            shortName: "LW",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 157,
            name: "Spain",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/157.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 12000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,87",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1359586800,
        contractUntil: false,
        captain: false,
        lastClub: {
          id: "398",
          name: "Lazio",
          fullName: "SS Lazio",
          image:
            "https://tmssl.akamaized.net/images/wappen/medium/398.png?lm=1601537785",
          nationalTeam: "",
          flag: null,
          marketValue: null,
          mainCompetition: null,
        },
        isLoan: true,
        wasLoan: null,
        id: "39118",
        name: "Juan Pablo Carrizo",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/39118-1410340416.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 28,
        dateOfBirth: 452642400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/juan-pablo-carrizo-1403768526-875.jpg?lm=1483605524",
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,95",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1293836400,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "44327",
        name: "Andrea Ranocchia",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/44327-1663659408.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 24,
        dateOfBirth: 571964400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/andrea-ranocchia-ac-monza-2022-1663760389-92999.jpg?lm=1663760406",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 17000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,78",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1277935200,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "45581",
        name: "Joel Obi",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/45581-1630590262.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 21,
        dateOfBirth: 674863200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/joel-obi-salernitana-1634054068-72682.jpg?lm=1634054080",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: {
            id: "9",
            name: "Left Midfield",
            shortName: "LM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 124,
            name: "Nigeria",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/124.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 5500000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,77",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1359586800,
        contractUntil: 1814306400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "51471",
        name: "Mateo Kovacic",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/51471-1682668192.jpg?lm=1",
        imageLarge: null,
        imageSource: "IMAGO",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 768175200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/mateo-kovacic-1512038707-12944.jpg?lm=1512038720",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          third: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 37,
            name: "Croatia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/37.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 15000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,67",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1345672800,
        contractUntil: 1735599600,
        captain: false,
        lastClub: {
          id: "6195",
          name: "SSC Napoli",
          fullName: "SSC Napoli",
          image:
            "https://tmssl.akamaized.net/images/wappen/medium/6195.png?lm=1688982522",
          nationalTeam: "",
          flag: null,
          marketValue: null,
          mainCompetition: null,
        },
        isLoan: true,
        wasLoan: null,
        id: "52266",
        name: "Walter Gargano",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/52266-1581878477.jpg?lm=1",
        imageLarge: null,
        imageSource: "www.peñarol.org ",
        shirtNumber: null,
        age: 27,
        dateOfBirth: 459381600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/walter-gargano-1418293672-3857.jpg?lm=1483605884",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 179,
            name: "Uruguay",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/179.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 7500000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,70",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1310680800,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "54149",
        name: "Jonathan",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/54149-1410340317.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 26,
        dateOfBirth: 509842800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/jonathan-cicero-moreira-1406843665-1924.jpg?lm=1483605660",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          second: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 26,
            name: "Brazil",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 4000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,80",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1346018400,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "54859",
        name: "Álvaro Pereira",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/s_54859_46_2013_09_09_1.jpg?lm=1",
        imageLarge: null,
        imageSource: "Getty Images",
        shirtNumber: null,
        age: 26,
        dateOfBirth: 501980400,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/pereira-alvaro-inter-2013-1704211839-125337.jpg?lm=1704211854",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
          second: {
            id: "9",
            name: "Left Midfield",
            shortName: "LM",
            group: "Midfielder",
          },
          third: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
        },
        nationalities: [
          {
            id: 179,
            name: "Uruguay",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/179.png?lm=1520611569",
          },
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 10000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,88",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "70580",
        name: "Raffaele Di Gennaro",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/70580-1692961707.jpg?lm=1",
        imageLarge: null,
        imageSource: "IMAGO",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 749602800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/raffaele-di-gennaro-1406840607-1888.jpg?lm=1483605657",
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 300000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,92",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1246399200,
        contractUntil: 1748642400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "73090",
        name: "Vid Belec",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/73090-1449136513.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 22,
        dateOfBirth: 644623200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/vid-belec-salernitana-1634301070-72944.jpg?lm=1634301084",
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 155,
            name: "Slovenia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/155.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1400000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,88",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1309903200,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "76077",
        name: "Ricardo Álvarez",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/76077-1638748437.JPG?lm=1",
        imageLarge: null,
        imageSource: "fotobaires.com",
        shirtNumber: null,
        age: 24,
        dateOfBirth: 576799200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/ricardo-alvarez-velez-sarsfield-2021-1638746235-76070.jpg?lm=1638746247",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 9000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,84",
        foot: "left",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "76895",
        name: "Simone Pasa",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/76895-1663960353.jpg?lm=1",
        imageLarge: null,
        imageSource: "riminifc.it",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 759106800,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,70",
        foot: "both",
        injury: null,
        suspension: null,
        joined: 1309471200,
        contractUntil: 1738278000,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "79522",
        name: "Yuto Nagatomo",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/79522-1572951921.jpg?lm=1",
        imageLarge: null,
        imageSource: "Galatasaray SK",
        shirtNumber: null,
        age: 25,
        dateOfBirth: 526860000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/yuto-nagatomo-galatasaray-1589791544-38797.jpg?lm=1589791537",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
          second: {
            id: "9",
            name: "Left Midfield",
            shortName: "LM",
            group: "Midfielder",
          },
          third: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
        },
        nationalities: [
          {
            id: 77,
            name: "Japan",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/77.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 12000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,72",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1216764000,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "80444",
        name: "Philippe Coutinho",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/80444-1640621762.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 20,
        dateOfBirth: 708300000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/philippe-coutinho-al-duhail-sc-2023-2024-1701179747-122743.jpg?lm=1701179765",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          second: {
            id: "11",
            name: "Left Winger",
            shortName: "LW",
            group: "Striker",
          },
          third: {
            id: "12",
            name: "Right Winger",
            shortName: "RW",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 26,
            name: "Brazil",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
          },
          {
            id: 136,
            name: "Portugal",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/136.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 10000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,84",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1327446000,
        contractUntil: 1814306400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "95438",
        name: "Marko Livaja",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/95438-1662878058.jpg?lm=1",
        imageLarge: null,
        imageSource: "www.hajduk.hr",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 746316000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/marko-livaja-croatia-2022-1664139039-93179.jpg?lm=1664139428",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: {
            id: "13",
            name: "Second Striker",
            shortName: "SS",
            group: "Striker",
          },
          third: {
            id: "11",
            name: "Left Winger",
            shortName: "LW",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 37,
            name: "Croatia",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/37.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 3300000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,87",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1359586800,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "119164",
        name: "Ezequiel Schelotto",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/119164-1478085509.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 23,
        dateOfBirth: 611877600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/ezequiel-schelotto-brighton-hove-albion-1612446621-55943.jpg?lm=1612446643",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          second: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
          third: {
            id: "12",
            name: "Right Winger",
            shortName: "RW",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
          {
            id: 9,
            name: "Argentina",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/9.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 5000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,85",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1327878000,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "121985",
        name: "Juan Jesus",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/121985-1630496408.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 21,
        dateOfBirth: 676504800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/juan-jesus-napoli-1633953913-72526.jpg?lm=1633953923",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
          third: null,
        },
        nationalities: [
          {
            id: 26,
            name: "Brazil",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 11000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,85",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "124560",
        name: "Samuele Longo",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/124560-1598857109.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 20,
        dateOfBirth: 695170800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/samuele-longo-1411034302-2728.jpg?lm=1483605754",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 2000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,87",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "126114",
        name: "Lukas Spendlhofer",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/126114-1705431699.png?lm=1",
        imageLarge: null,
        imageSource: "www.termalica.brukbet.com",
        shirtNumber: null,
        age: 19,
        dateOfBirth: 738972000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/lukas-spendlhofer-sturm-graz-1601624258-48258.jpg?lm=1601624267",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          third: null,
        },
        nationalities: [
          {
            id: 127,
            name: "Austria",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/127.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 250000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,78",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "135217",
        name: "Patrick Olsen",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/135217-1668768618.png?lm=1",
        imageLarge: null,
        imageSource: "www.slaskwroclaw.pl",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 767052000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/patrick-olsen-aarhus-gf-1644927882-80294.jpg?lm=1644927914",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 39,
            name: "Denmark",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/39.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 350000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,83",
        foot: "both",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "136130",
        name: "Andrea Romanò",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/136130-1549046773.jpg?lm=1",
        imageLarge: null,
        imageSource: "fc-suedtirol.com",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 743378400,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 500000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,78",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: 1782770400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "140757",
        name: "Daniel Bessa",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/140757-1630661042.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 19,
        dateOfBirth: 726966000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/daniel-bessa-hellas-verona-1612868147-56245.jpg?lm=1612868211",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "9",
            name: "Left Midfield",
            shortName: "LM",
            group: "Midfielder",
          },
          third: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
          {
            id: 26,
            name: "Brazil",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 800000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,89",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "160986",
        name: "Matteo Bianchetti",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/160986-1663683697.jpg?lm=1",
        imageLarge: null,
        imageSource: "IMAGO",
        shirtNumber: null,
        age: 19,
        dateOfBirth: 732322800,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/matteo-bianchetti-cremonese-1613740631-57003.jpg?lm=1613740656",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,90",
        foot: "left",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "162939",
        name: "Matteo Colombi",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/162939-1673394323.jpg?lm=1",
        imageLarge: null,
        imageSource: "cjarlinsmuzane.it",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 771458400,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 100000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,87",
        foot: "left",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "164534",
        name: "Francesco Forte",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/164534-1550651454.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 19,
        dateOfBirth: 736207200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/francesco-forte-benevento-1645096482-80409.jpg?lm=1645096518",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "14",
            name: "Centre-Forward",
            shortName: "CF",
            group: "Striker",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 100000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,78",
        foot: "left",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "184894",
        name: "Alfred Duncan",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/184894-1663591729.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 19,
        dateOfBirth: 731718000,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/alfred-duncan-fiorentina-1633962064-72544.jpg?lm=1633962160",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 54,
            name: "Ghana",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/54.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 5000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,78",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "199902",
        name: "Andrea Bandini",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/199902-1553763763.jpg?lm=1",
        imageLarge: null,
        imageSource: "riminifc.it",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 761353200,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          second: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
          third: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 150000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "199924",
        name: "Giovanni Terrani",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/199924-1698789945.png?lm=1",
        imageLarge: null,
        imageSource: "actrento.com",
        shirtNumber: null,
        age: 17,
        dateOfBirth: 781916400,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "11",
            name: "Left Winger",
            shortName: "LW",
            group: "Striker",
          },
          second: {
            id: "12",
            name: "Right Winger",
            shortName: "RW",
            group: "Striker",
          },
          third: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 100000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,84",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "201040",
        name: "Marco Benassi",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/201040-1644233941.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 17,
        dateOfBirth: 778975200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/marco-benassi-fiorentina-2022-2223-1674114659-100312.jpg?lm=1674114673",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
          third: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 2200000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,72",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "205677",
        name: "Luca Garritano",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/205677-1695107242.jpg?lm=1",
        imageLarge: null,
        imageSource: "IMAGO",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 760921200,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/luca-garritano-frosinone-1637152071-74868.jpg?lm=1637152104",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          second: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          third: {
            id: "11",
            name: "Left Winger",
            shortName: "LW",
            group: "Striker",
          },
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 900000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,88",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1710941355,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "206699",
        name: "Matteo Cincilla",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/s_206699_24898_2014_01_06_1.jpg?lm=1",
        imageLarge: null,
        imageSource: "acrenate.it",
        shirtNumber: null,
        age: 17,
        dateOfBirth: 782953200,
        heroImage: null,
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 50000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,88",
        foot: "right",
        injury: null,
        suspension: null,
        joined: 1341093600,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "207715",
        name: "Ibrahima Mbaye",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/207715-1595929552.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 17,
        dateOfBirth: 785199600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/ibrahima-mbaye-bologna-1634051805-72656.jpg?lm=1634051842",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          second: {
            id: "8",
            name: "Right Midfield",
            shortName: "RM",
            group: "Midfielder",
          },
          third: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
        },
        nationalities: [
          {
            id: 149,
            name: "Senegal",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/149.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 1000000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,74",
        foot: "left",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "230826",
        name: "Gennaro Acampora",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/230826-1632543544.jpg?lm=1",
        imageLarge: null,
        imageSource: "beneventocalcio.club",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 764892000,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 75000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,76",
        foot: "left",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1751234400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "240190",
        name: "Niccolò Belloni",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/240190-1667903443.jpg?lm=1",
        imageLarge: null,
        imageSource: "acrsiena1904.it",
        shirtNumber: null,
        age: 17,
        dateOfBirth: 773791200,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "12",
            name: "Right Winger",
            shortName: "RW",
            group: "Striker",
          },
          second: {
            id: "10",
            name: "Attacking Midfield",
            shortName: "AM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 250000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,91",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "240194",
        name: "Raffaele Dalle Vedove",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/s_240194_5380_2013_03_16_1.jpg?lm=1",
        imageLarge: null,
        imageSource: "inter.it",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 762390000,
        heroImage: null,
        isGoalkeeper: true,
        positions: {
          first: {
            id: "1",
            name: "Goalkeeper",
            shortName: "GK",
            group: "Goalkeeper",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 75000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1710941355,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "240195",
        name: "Yago Del Piero",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/240195-1584709875.jpg?lm=1",
        imageLarge: null,
        imageSource: "imago images",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 758502000,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "7",
            name: "Central Midfield",
            shortName: "CM",
            group: "Midfielder",
          },
          second: {
            id: "6",
            name: "Defensive Midfield",
            shortName: "DM",
            group: "Midfielder",
          },
          third: null,
        },
        nationalities: [
          {
            id: 26,
            name: "Brazil",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/26.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 100000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,81",
        foot: "right",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: 1719698400,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "240197",
        name: "Isaac Donkor",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/240197-1664103782.png?lm=1",
        imageLarge: null,
        imageSource: "sakaryaspor.org.tr",
        shirtNumber: null,
        age: 16,
        dateOfBirth: 808437600,
        heroImage:
          "https://tmssl.akamaized.net/images/foto/normal/isaac-donkor-1418297642-3867.jpg?lm=1483605884",
        isGoalkeeper: false,
        positions: {
          first: {
            id: "3",
            name: "Centre-Back",
            shortName: "CB",
            group: "Defender",
          },
          second: {
            id: "5",
            name: "Right-Back",
            shortName: "RB",
            group: "Defender",
          },
          third: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
        },
        nationalities: [
          {
            id: 54,
            name: "Ghana",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/54.png?lm=1520611569",
          },
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 250000,
          currency: "€",
          progression: null,
        },
      },
      {
        height: "1,81",
        foot: "left",
        injury: null,
        suspension: null,
        joined: false,
        contractUntil: false,
        captain: false,
        lastClub: null,
        isLoan: null,
        wasLoan: null,
        id: "240289",
        name: "Marco Ferrara",
        image:
          "https://img.a.transfermarkt.technology/portrait/medium/240289-1539359935.jpg?lm=1",
        imageLarge: null,
        imageSource: "casertanafc.it",
        shirtNumber: null,
        age: 18,
        dateOfBirth: 768088800,
        heroImage: null,
        isGoalkeeper: false,
        positions: {
          first: {
            id: "4",
            name: "Left-Back",
            shortName: "LB",
            group: "Defender",
          },
          second: null,
          third: null,
        },
        nationalities: [
          {
            id: 75,
            name: "Italy",
            image:
              "https://tmssl.akamaized.net/images/flagge/small/75.png?lm=1520611569",
          },
        ],
        marketValue: {
          value: 50000,
          currency: "€",
          progression: null,
        },
      },
    ],
  },
};
